// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "pronto-hubble/api/v1/models"
)

// DeleteClusterNoContentCode is the HTTP code returned for type DeleteClusterNoContent
const DeleteClusterNoContentCode int = 204

/*DeleteClusterNoContent Deleted

swagger:response deleteClusterNoContent
*/
type DeleteClusterNoContent struct {
}

// NewDeleteClusterNoContent creates DeleteClusterNoContent with default headers values
func NewDeleteClusterNoContent() *DeleteClusterNoContent {

	return &DeleteClusterNoContent{}
}

// WriteResponse to the client
func (o *DeleteClusterNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteClusterDefault error

swagger:response deleteClusterDefault
*/
type DeleteClusterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteClusterDefault creates DeleteClusterDefault with default headers values
func NewDeleteClusterDefault(code int) *DeleteClusterDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteClusterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete cluster default response
func (o *DeleteClusterDefault) WithStatusCode(code int) *DeleteClusterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete cluster default response
func (o *DeleteClusterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete cluster default response
func (o *DeleteClusterDefault) WithPayload(payload *models.Error) *DeleteClusterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster default response
func (o *DeleteClusterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
