// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// JoinClusterHandlerFunc turns a function with the right signature into a join cluster handler
type JoinClusterHandlerFunc func(JoinClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn JoinClusterHandlerFunc) Handle(params JoinClusterParams) middleware.Responder {
	return fn(params)
}

// JoinClusterHandler interface for that can handle valid join cluster params
type JoinClusterHandler interface {
	Handle(JoinClusterParams) middleware.Responder
}

// NewJoinCluster creates a new http.Handler for the join cluster operation
func NewJoinCluster(ctx *middleware.Context, handler JoinClusterHandler) *JoinCluster {
	return &JoinCluster{Context: ctx, Handler: handler}
}

/*JoinCluster swagger:route PUT /clusters/{id}/join clusters joinCluster

JoinCluster join cluster API

*/
type JoinCluster struct {
	Context *middleware.Context
	Handler JoinClusterHandler
}

func (o *JoinCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewJoinClusterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
