// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// LeaveHandlerFunc turns a function with the right signature into a leave handler
type LeaveHandlerFunc func(LeaveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LeaveHandlerFunc) Handle(params LeaveParams) middleware.Responder {
	return fn(params)
}

// LeaveHandler interface for that can handle valid leave params
type LeaveHandler interface {
	Handle(LeaveParams) middleware.Responder
}

// NewLeave creates a new http.Handler for the leave operation
func NewLeave(ctx *middleware.Context, handler LeaveHandler) *Leave {
	return &Leave{Context: ctx, Handler: handler}
}

/*Leave swagger:route PUT /clusters/{id}/leave clusters leave

Leave leave API

*/
type Leave struct {
	Context *middleware.Context
	Handler LeaveHandler
}

func (o *Leave) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLeaveParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
