// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "pronto-hubble/api/v1/models"
)

// CreateDeviceCreatedCode is the HTTP code returned for type CreateDeviceCreated
const CreateDeviceCreatedCode int = 201

/*CreateDeviceCreated Created

swagger:response createDeviceCreated
*/
type CreateDeviceCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ID `json:"body,omitempty"`
}

// NewCreateDeviceCreated creates CreateDeviceCreated with default headers values
func NewCreateDeviceCreated() *CreateDeviceCreated {

	return &CreateDeviceCreated{}
}

// WithPayload adds the payload to the create device created response
func (o *CreateDeviceCreated) WithPayload(payload *models.ID) *CreateDeviceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create device created response
func (o *CreateDeviceCreated) SetPayload(payload *models.ID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDeviceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateDeviceDefault error

swagger:response createDeviceDefault
*/
type CreateDeviceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateDeviceDefault creates CreateDeviceDefault with default headers values
func NewCreateDeviceDefault(code int) *CreateDeviceDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateDeviceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create device default response
func (o *CreateDeviceDefault) WithStatusCode(code int) *CreateDeviceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create device default response
func (o *CreateDeviceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create device default response
func (o *CreateDeviceDefault) WithPayload(payload *models.Error) *CreateDeviceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create device default response
func (o *CreateDeviceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDeviceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
