// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateDeviceHandlerFunc turns a function with the right signature into a create device handler
type CreateDeviceHandlerFunc func(CreateDeviceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDeviceHandlerFunc) Handle(params CreateDeviceParams) middleware.Responder {
	return fn(params)
}

// CreateDeviceHandler interface for that can handle valid create device params
type CreateDeviceHandler interface {
	Handle(CreateDeviceParams) middleware.Responder
}

// NewCreateDevice creates a new http.Handler for the create device operation
func NewCreateDevice(ctx *middleware.Context, handler CreateDeviceHandler) *CreateDevice {
	return &CreateDevice{Context: ctx, Handler: handler}
}

/*RegisterDevice swagger:route POST /devices devices createDevice

RegisterDevice create device API

*/
type CreateDevice struct {
	Context *middleware.Context
	Handler CreateDeviceHandler
}

func (o *CreateDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateDeviceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
