// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDeviceHandlerFunc turns a function with the right signature into a delete device handler
type DeleteDeviceHandlerFunc func(DeleteDeviceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDeviceHandlerFunc) Handle(params DeleteDeviceParams) middleware.Responder {
	return fn(params)
}

// DeleteDeviceHandler interface for that can handle valid delete device params
type DeleteDeviceHandler interface {
	Handle(DeleteDeviceParams) middleware.Responder
}

// NewDeleteDevice creates a new http.Handler for the delete device operation
func NewDeleteDevice(ctx *middleware.Context, handler DeleteDeviceHandler) *DeleteDevice {
	return &DeleteDevice{Context: ctx, Handler: handler}
}

/*DeleteDevice swagger:route DELETE /devices/{id} devices deleteDevice

DeleteDevice delete device API

*/
type DeleteDevice struct {
	Context *middleware.Context
	Handler DeleteDeviceHandler
}

func (o *DeleteDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDeviceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
