// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"pronto-hubble/api/v1/restapi/operations/clusters"
	"pronto-hubble/api/v1/restapi/operations/devices"
	"pronto-hubble/api/v1/restapi/operations/users"
)

// NewProntoHubbleAPI creates a new ProntoHubble instance
func NewProntoHubbleAPI(spec *loads.Document) *ProntoHubbleAPI {
	return &ProntoHubbleAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		ClustersCreateClusterHandler: clusters.CreateClusterHandlerFunc(func(params clusters.CreateClusterParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersCreateCluster has not yet been implemented")
		}),
		DevicesCreateDeviceHandler: devices.CreateDeviceHandlerFunc(func(params devices.CreateDeviceParams) middleware.Responder {
			return middleware.NotImplemented("operation DevicesCreateDevice has not yet been implemented")
		}),
		UsersCreateUserHandler: users.CreateUserHandlerFunc(func(params users.CreateUserParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersCreateUser has not yet been implemented")
		}),
		ClustersDeleteClusterHandler: clusters.DeleteClusterHandlerFunc(func(params clusters.DeleteClusterParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersDeleteCluster has not yet been implemented")
		}),
		DevicesDeleteDeviceHandler: devices.DeleteDeviceHandlerFunc(func(params devices.DeleteDeviceParams) middleware.Responder {
			return middleware.NotImplemented("operation DevicesDeleteDevice has not yet been implemented")
		}),
		UsersDeleteUserHandler: users.DeleteUserHandlerFunc(func(params users.DeleteUserParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersDeleteUser has not yet been implemented")
		}),
		ClustersGetClusterHandler: clusters.GetClusterHandlerFunc(func(params clusters.GetClusterParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersGetCluster has not yet been implemented")
		}),
		DevicesGetDeviceHandler: devices.GetDeviceHandlerFunc(func(params devices.GetDeviceParams) middleware.Responder {
			return middleware.NotImplemented("operation DevicesGetDevice has not yet been implemented")
		}),
		UsersGetUserHandler: users.GetUserHandlerFunc(func(params users.GetUserParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersGetUser has not yet been implemented")
		}),
		ClustersJoinHandler: clusters.JoinHandlerFunc(func(params clusters.JoinParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersJoin has not yet been implemented")
		}),
		ClustersLeaveHandler: clusters.LeaveHandlerFunc(func(params clusters.LeaveParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersLeave has not yet been implemented")
		}),
		ClustersListClustersHandler: clusters.ListClustersHandlerFunc(func(params clusters.ListClustersParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersListClusters has not yet been implemented")
		}),
		DevicesListDevicesHandler: devices.ListDevicesHandlerFunc(func(params devices.ListDevicesParams) middleware.Responder {
			return middleware.NotImplemented("operation DevicesListDevices has not yet been implemented")
		}),
		UsersListUsersHandler: users.ListUsersHandlerFunc(func(params users.ListUsersParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersListUsers has not yet been implemented")
		}),
		ClustersUpdateClusterHandler: clusters.UpdateClusterHandlerFunc(func(params clusters.UpdateClusterParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersUpdateCluster has not yet been implemented")
		}),
		DevicesUpdateDeviceHandler: devices.UpdateDeviceHandlerFunc(func(params devices.UpdateDeviceParams) middleware.Responder {
			return middleware.NotImplemented("operation DevicesUpdateDevice has not yet been implemented")
		}),
		UsersUpdateUserHandler: users.UpdateUserHandlerFunc(func(params users.UpdateUserParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersUpdateUser has not yet been implemented")
		}),
	}
}

/*ProntoHubbleAPI Hubble service for Pronto */
type ProntoHubbleAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ClustersCreateClusterHandler sets the operation handler for the create cluster operation
	ClustersCreateClusterHandler clusters.CreateClusterHandler
	// DevicesCreateDeviceHandler sets the operation handler for the create device operation
	DevicesCreateDeviceHandler devices.CreateDeviceHandler
	// UsersCreateUserHandler sets the operation handler for the create user operation
	UsersCreateUserHandler users.CreateUserHandler
	// ClustersDeleteClusterHandler sets the operation handler for the delete cluster operation
	ClustersDeleteClusterHandler clusters.DeleteClusterHandler
	// DevicesDeleteDeviceHandler sets the operation handler for the delete device operation
	DevicesDeleteDeviceHandler devices.DeleteDeviceHandler
	// UsersDeleteUserHandler sets the operation handler for the delete user operation
	UsersDeleteUserHandler users.DeleteUserHandler
	// ClustersGetClusterHandler sets the operation handler for the get cluster operation
	ClustersGetClusterHandler clusters.GetClusterHandler
	// DevicesGetDeviceHandler sets the operation handler for the get device operation
	DevicesGetDeviceHandler devices.GetDeviceHandler
	// UsersGetUserHandler sets the operation handler for the get user operation
	UsersGetUserHandler users.GetUserHandler
	// ClustersJoinHandler sets the operation handler for the join operation
	ClustersJoinHandler clusters.JoinHandler
	// ClustersLeaveHandler sets the operation handler for the leave operation
	ClustersLeaveHandler clusters.LeaveHandler
	// ClustersListClustersHandler sets the operation handler for the list clusters operation
	ClustersListClustersHandler clusters.ListClustersHandler
	// DevicesListDevicesHandler sets the operation handler for the list devices operation
	DevicesListDevicesHandler devices.ListDevicesHandler
	// UsersListUsersHandler sets the operation handler for the list users operation
	UsersListUsersHandler users.ListUsersHandler
	// ClustersUpdateClusterHandler sets the operation handler for the update cluster operation
	ClustersUpdateClusterHandler clusters.UpdateClusterHandler
	// DevicesUpdateDeviceHandler sets the operation handler for the update device operation
	DevicesUpdateDeviceHandler devices.UpdateDeviceHandler
	// UsersUpdateUserHandler sets the operation handler for the update user operation
	UsersUpdateUserHandler users.UpdateUserHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *ProntoHubbleAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ProntoHubbleAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *ProntoHubbleAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *ProntoHubbleAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ProntoHubbleAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ProntoHubbleAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ProntoHubbleAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ProntoHubbleAPI
func (o *ProntoHubbleAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ClustersCreateClusterHandler == nil {
		unregistered = append(unregistered, "clusters.CreateClusterHandler")
	}

	if o.DevicesCreateDeviceHandler == nil {
		unregistered = append(unregistered, "devices.CreateDeviceHandler")
	}

	if o.UsersCreateUserHandler == nil {
		unregistered = append(unregistered, "users.CreateUserHandler")
	}

	if o.ClustersDeleteClusterHandler == nil {
		unregistered = append(unregistered, "clusters.DeleteClusterHandler")
	}

	if o.DevicesDeleteDeviceHandler == nil {
		unregistered = append(unregistered, "devices.DeleteDeviceHandler")
	}

	if o.UsersDeleteUserHandler == nil {
		unregistered = append(unregistered, "users.DeleteUserHandler")
	}

	if o.ClustersGetClusterHandler == nil {
		unregistered = append(unregistered, "clusters.GetClusterHandler")
	}

	if o.DevicesGetDeviceHandler == nil {
		unregistered = append(unregistered, "devices.GetDeviceHandler")
	}

	if o.UsersGetUserHandler == nil {
		unregistered = append(unregistered, "users.GetUserHandler")
	}

	if o.ClustersJoinHandler == nil {
		unregistered = append(unregistered, "clusters.JoinHandler")
	}

	if o.ClustersLeaveHandler == nil {
		unregistered = append(unregistered, "clusters.LeaveHandler")
	}

	if o.ClustersListClustersHandler == nil {
		unregistered = append(unregistered, "clusters.ListClustersHandler")
	}

	if o.DevicesListDevicesHandler == nil {
		unregistered = append(unregistered, "devices.ListDevicesHandler")
	}

	if o.UsersListUsersHandler == nil {
		unregistered = append(unregistered, "users.ListUsersHandler")
	}

	if o.ClustersUpdateClusterHandler == nil {
		unregistered = append(unregistered, "clusters.UpdateClusterHandler")
	}

	if o.DevicesUpdateDeviceHandler == nil {
		unregistered = append(unregistered, "devices.UpdateDeviceHandler")
	}

	if o.UsersUpdateUserHandler == nil {
		unregistered = append(unregistered, "users.UpdateUserHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ProntoHubbleAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ProntoHubbleAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *ProntoHubbleAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *ProntoHubbleAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *ProntoHubbleAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ProntoHubbleAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the pronto hubble API
func (o *ProntoHubbleAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *ProntoHubbleAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/clusters"] = clusters.NewCreateCluster(o.context, o.ClustersCreateClusterHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/devices"] = devices.NewCreateDevice(o.context, o.DevicesCreateDeviceHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users"] = users.NewCreateUser(o.context, o.UsersCreateUserHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/clusters/{id}"] = clusters.NewDeleteCluster(o.context, o.ClustersDeleteClusterHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/devices/{id}"] = devices.NewDeleteDevice(o.context, o.DevicesDeleteDeviceHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{id}"] = users.NewDeleteUser(o.context, o.UsersDeleteUserHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/clusters/{id}"] = clusters.NewGetCluster(o.context, o.ClustersGetClusterHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/devices/{id}"] = devices.NewGetDevice(o.context, o.DevicesGetDeviceHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{id}"] = users.NewGetUser(o.context, o.UsersGetUserHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/clusters/{id}/join"] = clusters.NewJoin(o.context, o.ClustersJoinHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/clusters/{id}/leave"] = clusters.NewLeave(o.context, o.ClustersLeaveHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/clusters"] = clusters.NewListClusters(o.context, o.ClustersListClustersHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/devices"] = devices.NewListDevices(o.context, o.DevicesListDevicesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users"] = users.NewListUsers(o.context, o.UsersListUsersHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/clusters/{id}"] = clusters.NewUpdateCluster(o.context, o.ClustersUpdateClusterHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/devices/{id}"] = devices.NewUpdateDevice(o.context, o.DevicesUpdateDeviceHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/{id}"] = users.NewUpdateUser(o.context, o.UsersUpdateUserHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ProntoHubbleAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *ProntoHubbleAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *ProntoHubbleAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *ProntoHubbleAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
